# Generated by Django 2.1.3 on 2018-11-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnwserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Treść')),
                ('correct', models.BooleanField(verbose_name='Zgodność')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.IntegerField(choices=[(1, 'Wykład 1'), (2, 'Wykład 2'), (3, 'Wykład 3'), (4, 'Wykład 4'), (5, 'Wykład 5')], max_length=1, verbose_name='Wykład')),
                ('question_text', models.TextField(unique=True, verbose_name='Pytanie')),
                ('explanation', models.TextField(verbose_name='Wytłumaczenie')),
            ],
        ),
        migrations.AddField(
            model_name='anwserquiz',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anwsers', related_query_name='answer', to='quizzes.QuestionQuiz'),
        ),
    ]
