# Generated by Django 2.1.3 on 2018-11-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionquiz',
            name='lecture',
            field=models.IntegerField(choices=[(1, 'Wykład 1'), (2, 'Wykład 2'), (3, 'Wykład 3'), (4, 'Wykład 4'), (5, 'Wykład 5')], verbose_name='Wykład'),
        ),
    ]
